stacks:
  root: <%= File.join(Rails.root, "spec", "fixtures", "stacks") %>

s3:
  access_key_id: minio-user
  secret_access_key: minio-password
  bucket: stacks-test
  endpoint: http://localhost:9000

content_search:
  url: "http://example.com/content_search/%{druid}/search"

resource_cache:
  enabled: false
